spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventarymgtschemadb
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: false    
stock:
  transportType: air
  slaDays: 900
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://discoveryserver1.com:8761/eureka,http://discoveryserver2.com:8762/eureka, http://discoveryserver3.com:8763/eureka